name: Enforce Issue Template

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  enforce-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue was created via the issue form
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueBody = context.payload.issue.body;

            // Output the issue body for debugging
            console.log('Issue Body:', issueBody);

            // Define required sections that should be present in the issue template
            const requiredSections = [
              '### Expected Behavior',
              '### Actual Behavior',
              '### Steps to Reproduce'
            ];

            // Check if all required sections are present
            const missingSections = requiredSections.filter(section => !issueBody.includes(section));

            if (missingSections.length > 0) {
              // Post a comment explaining why the issue is being closed
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `Thank you for opening an issue. However, it seems that you did not use the provided issue template or did not fill out all required sections. Please edit your issue to include all required sections. This issue will be closed.`,
              });

              // Close the issue
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                state: 'closed',
              });
            } else {
              console.log('Issue contains all required sections.');
            }
