name: Enforce Issue Template

on:
  issues:
    types: [opened]

permissions:
  issues: write  # Add this line to grant write permission to issues

jobs:
  enforce-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue was created via the issue form
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueBody = context.payload.issue.body;

            // Expected HTML comment marker from the issue form
            const expectedMarker = '<!-- issue:bug_report_v1 -->';

            // Check if the issue body contains the expected marker
            if (!issueBody.includes(expectedMarker)) {
              // Post a comment explaining why the issue is being closed
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `Thank you for opening an issue. However, it appears that you did not use our issue form. Please resubmit your issue using the provided issue form so we have all the necessary information to assist you. This issue will now be closed.`,
              });

              // Close the issue
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                state: 'closed',
              });
            }
